version: "2"

services:
  mongo:
    image: mongo
    ports:
      - "10101:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "10100:6379"
    volumes:
      - redis-data:/data

  redis2:
    image: redis:3.2-alpine
    volumes:
      - redis2-data:/data
    ports:
      - "10102:6379"

  redis-sentinel:
    build:
      context: ./redis-sentinel
    volumes:
      - redis-sentinel-data:/data
    links:
      - redis2
    ports:
      - "10103:26379"

  docker-host:
    image: docker:stable-dind
    privileged: true
    ports:
      - "1234:2375"

volumes:
  redis-data:
  redis2-data:
  redis-sentinel-data:
  mongo-data:
