version: "2"

services:
  mongo:
    image: mongo
    ports:
      - "10101:27017"
    volumes:
      - mongo-sample-data:/data/db
  redis:
    image: redis
    ports:
      - "10100:6379"
    volumes:
      - redis-sample-data:/data
  docker-host:
    image: docker:stable-dind
    privileged: true
  fastlane-api:
    image: heynemann/fastlane:latest
    ports:
      - "10000:10000"
    environment:
      - DOCKER_HOSTS=[{"match":"","hosts":["docker-host:2375"],"maxRunning":2}]
    depends_on:
      - mongo
      - redis
      - docker-host
    command: poetry run fastlane api -vvv
  fastlane-worker:
    image: heynemann/fastlane:latest
    environment:
      - DOCKER_HOSTS=[{"match":"","hosts":["docker-host:2375"],"maxRunning":2}]
    depends_on:
      - mongo
      - redis
      - docker-host
    command: poetry run fastlane worker -vvv

volumes:
  redis-sample-data:
  mongo-sample-data:
