version: "3"

services:
  mongo:
    image: mongo
    ports:
      - "27355:27017"
    volumes:
      - mongo-test-data:/data/db

  redis:
    image: redis
    ports:
      - "27356:6379"
    volumes:
      - redis-test-data:/data

  docker-host:
    image: docker:stable-dind
    privileged: true

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    env_file:
      - docker-compose-tests.env
    depends_on:
      - mongo
      - redis
      - docker-host
    command: poetry run fastlane api -vvv

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - docker-compose-tests.env
    depends_on:
      - mongo
      - redis
      - docker-host
      - api
    command: poetry run fastlane worker -vvv

volumes:
  redis-test-data:
  mongo-test-data:
